
DROP TABLE IF EXISTS Warehouses;
CREATE TABLE Warehouses (
	id INT AUTO_INCREMENT PRIMARY KEY,
	uuid VARCHAR(36) NOT NULL,
	client VARCHAR(50) NOT NULL,
	family VARCHAR(3) NOT NULL,
	size VARCHAR(2) NOT NULL
);

DROP TABLE IF EXISTS Racks;
CREATE TABLE Racks (
	id INT AUTO_INCREMENT PRIMARY KEY,
	uuid VARCHAR(36) NOT NULL,
	type VARCHAR(1) NOT NULL,
	warehouseId INT,
   FOREIGN KEY (warehouseId) REFERENCES Warehouses(id)
);

DROP TABLE IF EXISTS racks_type;
CREATE TABLE racks_type (
	id INT AUTO_INCREMENT PRIMARY KEY,
	family VARCHAR(3) NOT NULL,
	type VARCHAR(1) NOT NULL
);